name: EVM Contracts

on:
  push:
  - 'src/**'
  - 'test/**'
  pull_request:
  - 'src/**'
  - 'test/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        cp ./secrets.build.json ./.secrets.json
        yarn hardhat compile
        

    - name: Test
      run: |
        yarn hardhat test